#ifndef BSP_H_
#define BSP_H_

#include "stm32f0xx.h"
#include "common.h"
#include "usart.h"
#include "spi.h"
#include "can.h"
#include "flash.h"

#define BootTIMEOUT									(300000UL)
#define BSP_ALLBOARD_HSI_FREQUENCY	(8000000UL)


#define DBGMCU_ID_F04x							(0x00000445UL)
#define DBGMCU_ID_F03x							(0x00000444UL)

#define BSP_ALLBOARD_FLASH_START		(0x08000000UL)
#define BSP_ALLBOARD_BOOT_SIZE			(0x00001000UL)
#define BSP_ALLBOARD_BOOT_START			(BSP_ALLBOARD_FLASH_START)
#define BSP_ALLBOARD_BOOT_END				(BSP_ALLBOARD_BOOT_START + BSP_ALLBOARD_BOOT_SIZE)
#define BSP_SRAM_START 							(0x20000000UL)

#define BSP_VECTOR_SIZE_BYTES				(0x000000C0UL)
#define BSP_VECTOR_SIZE_WORDS				(BSP_VECTOR_SIZE_BYTES / sizeof(uint32_t))
	
#define BSP_PAGE_SIZE_BYTES       	(0x00000400UL)
#define BSP_APPLICATION_START				(BSP_ALLBOARD_BOOT_END)

#define BSP_ALLBOARD_PROGRAM_START	(BSP_ALLBOARD_BOOT_END)

#define BSP_PILOT_FLASH_SIZE_BYTES	(0x00003FFFUL)
#define BSP_PILOT_FLASH_END					(BSP_ALLBOARD_FLASH_START + BSP_PILOT_FLASH_SIZE_BYTES)
#define BSP_PILOT_PROGRAM_START			(BSP_ALLBOARD_BOOT_END)
#define BSP_PILOT_PROGRAM_SECTORS		((BSP_PILOT_FLASH_SIZE_BYTES + 1UL - BSP_ALLBOARD_BOOT_SIZE) / BSP_PAGE_SIZE_BYTES)
#define BSP_PILOT_UART_PORT					GPIOA
#define BSP_PILOT_UART_TX_PIN				2U
#define BSP_PILOT_UART_RX_PIN				3U
#define BSP_PILOT_UART_BAUD					57600U

#define BSP_TORQUE_FLASH_SIZE_BYTES	(0x00007FFFUL)
#define BSP_TORQUE_FLASH_END				(BSP_ALLBOARD_FLASH_START + BSP_TORQUE_FLASH_SIZE_BYTES)
#define BSP_TORQUE_PROGRAM_START		(BSP_ALLBOARD_BOOT_END)
#define BSP_TORQUE_PROGRAM_SECTORS	((BSP_TORQUE_FLASH_SIZE_BYTES + 1UL - BSP_ALLBOARD_BOOT_SIZE) / BSP_PAGE_SIZE_BYTES)
#define BSP_TORQUE_UART_PORT				GPIOA
#define BSP_TORQUE_UART_TX_PIN			2U
#define BSP_TORQUE_UART_RX_PIN			3U
#define BSP_TORQUE_UART_BAUD				1125000U
#define BSP_TORQUE_RCC_MULTIPLIER		(8UL)

#define BSP_BASE_FLASH_SIZE_BYTES		(0x00007FFFUL)
#define BSP_BASE_FLASH_END					(BSP_ALLBOARD_FLASH_START + BSP_BASE_FLASH_SIZE_BYTES)
#define BSP_BASE_PROGRAM_START			(BSP_ALLBOARD_BOOT_END)
#define BSP_BASE_PROGRAM_SECTORS		((BSP_BASE_FLASH_SIZE_BYTES + 1UL - BSP_ALLBOARD_BOOT_SIZE) / BSP_PAGE_SIZE_BYTES)
#define BSP_BASE_CAN_PORT						GPIOA
#define BSP_BASE_CAN_TX_PIN					12U
#define BSP_BASE_CAN_RX_PIN					11U
#define BSP_BASE_CAN_BAUD						1000000U
#define BSP_BASE_RCC_MULTIPLIER			(8UL)
#define BSP_BASE_CAN_ID							(8U)

#define BSP_NUCLEO_PROGRAM_END			(BSP_APPLICATION_START + 0x00007FFFUL)
#define BSP_NUCLEO_PROGRAM_SECTORS	((BSP_NUCLEO_PROGRAM_END + 1UL - BSP_ALLBOARD_BOOT_SIZE) / BSP_PAGE_SIZE_BYTES)
#define BSP_NUCLEO_UART_PORT				GPIOA
#define BSP_NUCLEO_UART_TX_PIN			2U
#define BSP_NUCLEO_UART_RX_PIN			15U
#define BSP_NUCLEO_UART_BAUD				57600U

#define BSP_CHECK_PORT							GPIOA
#define BSP_CHECK_PIN_6							6
#define BSP_CHECK_PIN_7							7

typedef struct timeouts{
	uint32_t ThreeSeconds;
	uint32_t StartApp;
	uint32_t EndOfComm;
}tTimeouts;

tBSPStruct* BSP_Init(void);
void BSP_DeInit(void);
#endif
